//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSocialMinijuegos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public Nullable<int> idUsuario { get; set; }
        public string NombreJuego { get; set; }
        public Nullable<int> Puntuacion { get; set; }
        public int IdPartida { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
